### ISSUE TITLE
Set-IBWAPIConfig fails on Windows 10 when PowerShell not run as Administrator

### ISSUE THREAD

**Issue by frankhecker** [rmbolger/Posh-IBWAPI#10]
Another issue from a PowerShell newbie (maybe this is expected behavior?): I was able to get Posh-IBWAPI working fine under Windows Server 2016 when logged in as Administrator: Install-Module worked without issue, and Set-IBWAPIConfig was able to set credentials. However I am not having the same success under Windows 10:

After doing Install-Module (which required an install of NuGet [?] that wasn't needed under WS2016), I was able to get Set-IBWAPIConfig to run properly only when explicitly telling Windows 10 to run PowerShell as Administrator. When I run PowerShell in the normal fashion and try the same Set-IBWAPIConfig command, I get the following error:

Invoke-RestMethod :
401 Authorization Required
Authorization Required
This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.
At C:\Program Files\WindowsPowerShell\Modules\Posh-IBWAPI\1.0\Public\Invoke-IBWAPI.ps1:67 char:17
+                 Invoke-RestMethod -Uri $Uri @opts
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

To the best of my knowledge I am using the same credentials in both cases. (I tried this multiple times.) My user account on Windows 10 has administrator access, and Get-ExecutionPolicy shows "Unrestricted" in both cases. The command I'm using is as follows:

 Set-IBWAPIConfig -host <gm> -version latest -cred (Get-Credential) -IgnoreCert

**Comment by rmbolger** [comment]
That's definitely odd. I do the vast majority of my testing from a couple different Win10 (1607) machines running Powershell as non-admin.

Was this a freshly launched PowerShell session that this failed on? Or had you been doing stuff with the module prior and then Set-IBWAPIConfig started failing?

I can see a potential problem in the code where if there was already an old WebSession saved with bad credentials and you call Set-IBWAPIConfig with new credentials, it wouldn't update the bad session before trying to get the latest version and fail with the 401.

But if this was a freshly launched PowerShell session, it should always create a fresh WebSession with the passed in credentials and I'm not sure what's wrong. Can you post the output of your $PSVersionTable variable so I can make sure it's not a weird bug specific to the Powershell version?

P.S. The NuGet dependency is normal. It's a Microsoft package management library that is basically a prereq for using Powershell Gallery as far as I know.

**Comment by rmbolger** [comment]
I pushed a new 1.0.1 release that has a potential fix to your issue if it was related to the problem I mentioned. You can update using `Update-Module Posh-IBWAPI` and that should pull down the new version.

If you still have a problem, post the output of `$PSVersionTable`. Also, run your `Set-IBWAPIConfig` command with the `-Verbose` flag and post that output as well. You'll probably need to sanitize private info like hostnames or IPs.

**Comment by frankhecker** [comment]
Starting a new PowerShell session apparently fixed the issue, even without downloading the new patch. Also, FYI, my $PSVersionTable is as follows:

Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Worked fine after updating Posh-IBWAPI also.

**Comment by rmbolger** [comment]
Excellent. I'm guessing the original issue was indeed related to the bug which is why the new session fixed it prior to the patch.
