### ISSUE TITLE
ConvertTo-JSON cmdlet is not working with other language characters like ü ö ä ç á etc.

### ISSUE THREAD

**Issue by friedlgrz** [rmbolger/Posh-IBWAPI#17]
ConvertTo-JSON cmdlet is not working with other language characters like ü ö ä ç á etc.
see: [see](https://social.technet.microsoft.com/Forums/lync/en-US/726ecbbf-3a65-4385-b520-eae93fd7e3e9/converttojson-cmdlet-is-not-working-with-other-language-characters-like-etcneed?forum=winserverpowershell)

Example:

// logon 
Set-IBWAPIConfig -WAPIhost ipam.xxx .at -WAPIVersion latest -credential (get-credential)

//read out with Special Characters -> works correctly
Get-IBObject -type network -filters "comment=Schönwies"

//write comment--> not work with Special Characters
Get-IBObject -type network -filters "network=x.x.x.x/24" |  Set-IBObject -Template @{comment = "Schönwies"}

ConvertTo-JSON are used in Invoke-IBFunction.ps1, New-IBObject.ps1, Set-IBObject.ps1.
I used the workarround from link at all "ConvertTo-JSON"-Calls in the three Files and it works perfect.
Please use the workaround also in your project.

**Comment by rmbolger** [comment]
Thank you for the bug report. It seems like the workaround should be pretty straightforward. I'll see what I can do.

**Comment by rmbolger** [comment]
This is now fixed in version 1.1.2.
