### ISSUE TITLE
Unable to add more aliases with Set-IBObject -template

### ISSUE THREAD

**Issue by resveld** [rmbolger/Posh-IBWAPI#30]
Hi,

Im trying to add multiple aliases through the powershell module, but it keeps failing.
Only way i can do it seems to be through the new object.

Here's a short version of code non-working:

```
$IBHOSTNAME = "servert.ronald.local"
$IBALIAS = "poffertjes.db.func.ronald.local,pizza.db.func.ronald.local"
$IBALIAS = $IBALIAS -split "," -match ".+db.func.ronald.local$" 
$IBCREATEALIAS = Get-IBObject -type record:host -filters "name=$IBHOSTNAME"
$IBCREATEALIAS | Set-IBObject -template @{aliases=@($IBALIAS)}
```

Working code:
```
$IBHOSTNAME = "servert.ronald.local"
$IBALIAS = "poffertjes.db.func.ronald.local,pizza.db.func.ronald.local,afhaalchinees.db.func.ronald.local"
$IBALIAS = $IBALIAS -split "," -match ".+db.func.ronald.local$" 
$IBIPADDRESS = Resolve-DnsName $IBHOSTNAME | Select-Object -Property IP4Address | ForEach-Object -Process {$_.IP4Address}
$IBDELETEHOST = Get-IBObject -type record:host -filters "name=$IBHOSTNAME"
$IBDELETEHOST | Remove-IBObject
$IBCREATEHOST = @{ name="$IBHOSTNAME"; ipv4addrs=@( @{ ipv4addr="$IBIPADDRESS" } ) }
if (!$NUMBEROFIBALIAS){
		Write-warning "No aliases to be add"
		$IBCREATEHOST = @{ name="$IBHOSTNAME"; ipv4addrs=@( @{ ipv4addr="$IBIPADDRESS" } ) }
		$IBCREATEHOST | New-IBObject -type record:host
		}

if ($NUMBEROFIBALIAS -eq 1){
		Write-warning "Adding 1 alias"
		$IBCREATEHOST.aliases = @($IBALIAS)
		$IBCREATEHOST | New-IBObject -type record:host
		}

if ($NUMBEROFIBALIAS -eq 2){
		Write-warning "Adding 2 aliases"
		$IBCREATEHOST.aliases = @($IBALIAS[0],$IBALIAS[1])
		$IBCREATEHOST | New-IBObject -type record:host
		}
```

It seems to me it should be able to work, got a clue?

thanks
Ronald

**Comment by rmbolger** [comment]
That's really strange. Your non-working code snippet works perfectly in my environment other than changing the value of `$IBHOSTNAME` to a host that exists. You're basically replacing the `aliases` array with a new array which should just work.

What error is it throwing for you? I'm also curious what version of NIOS you're on. I can try spinning up a test grid and see if I can reproduce the problem there.

**Comment by resveld** [comment]
Hi Ryan, I'll throw the errors tomorrow. We runnening 8.2 NIOS. Best regardsRonald-------- Oorspronkelijk bericht --------Onderwerp: Re: [rmbolger/Posh-IBWAPI] Unable to add more aliases with Set-IBObject -template (#30)Van: Ryan Bolger Aan: rmbolger/Posh-IBWAPI Cc: resveld ,Author That's really strange. Your non-working code snippet works perfectly in my environment other than changing the value of $IBHOSTNAME to a host that exists. You're basically replacing the aliases array with a new array which should just work.
What error is it throwing for you? I'm also curious what version of NIOS you're on. I can try spinning up a test grid and see if I can reproduce the problem there.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rmbolger/Posh-IBWAPI","title":"rmbolger/Posh-IBWAPI","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/rmbolger/Posh-IBWAPI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rmbolger in #30: That's really strange. Your non-working code snippet works perfectly in my environment other than changing the value of `$IBHOSTNAME` to a host that exists. You're basically replacing the `aliases` array with a new array which should just work.\r\n\r\nWhat error is it throwing for you? I'm also curious what version of NIOS you're on. I can try spinning up a test grid and see if I can reproduce the problem there."}],"action":{"name":"View Issue","url":"https://github.com/rmbolger/Posh-IBWAPI/issues/30#issuecomment-435895704"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rmbolger/Posh-IBWAPI/issues/30#issuecomment-435895704",
"url": "https://github.com/rmbolger/Posh-IBWAPI/issues/30#issuecomment-435895704",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [rmbolger/Posh-IBWAPI] Unable to add more aliases with Set-IBObject -template (#30)",
"sections": [
{
"text": "",
"activityTitle": "**Ryan Bolger**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@rmbolger",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"rmbolger/Posh-IBWAPI\",\n\"issueId\": 30,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"rmbolger/Posh-IBWAPI\",\n\"issueId\": 30\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/rmbolger/Posh-IBWAPI/issues/30#issuecomment-435895704"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 406441664\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by rmbolger** [comment]
I spun up a copy of NIOS 8.2.2 and couldn't reproduce the problem. So unless it's specific to a different minor version, there's likely something else going on.

**Comment by resveld** [comment]
We're running 8.2.7-372540.

Here's the error:
PS C:\temp> .\test.ps1

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
WARNING: Adding 2 aliases
AdmConProtoError: Input is not an object
At \\cak-bz.local\dfs\usr\admresveld\Mijn documenten\WindowsPowerShell\Modules\Posh-IBWAPI\1.5.0\Public\Invoke-IBWAPI.p
s1:141 char:13
+             throw [Exception] "$($wapiErr.Error)"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : AdmConProtoError: Input is not an object

**Comment by resveld** [comment]
Update, looks like it's working now. 
Seems like breaking up the aliases with the `` -split ","`` did the trick.
