### ISSUE TITLE
Question: add multiple extensible attributes on a single host record

### ISSUE THREAD

**Issue by resveld** [rmbolger/Posh-IBWAPI#31]
We have migrated from MS DNS to IB and use VRA to enroll and decomission the servers and thus the host records in DNS. 
For new hosts the IB sets 2 EA's:
VMNIC ID
VMware resource ID

I have a full list of both and try to add it to a host, but fail to do so (probably my lack of knowledge ;-)).
Is this possible?

I can set 1, but if I pass 2 variables it gives 1 value of nothing.

Working 1:
`$SETPIDHOST | Set-IBObject -template @{extattrs=@{"VMware resource ID"=@{value="$persistentid"}}}`

Failing one with 2 EA's:
`$SETPIDHOST | Set-IBObject -template @{extattrs=@{"VMware resource ID"=@{value="$persistentid"}}};@{"VMware NIC index"=@{value="$VMNIC"}}`
In this case it sets the resource id, but not the vmnixc id.
I've tried multiple combinations, but none works.

If i do the following in a PS session (not connection, just converting) then it looks like the syntax is ok:
`@{"VMware resource ID"=@{value="$persistentid"}}, @{"VMware NIC index"=@{value="$VMNIC"}} | convertto-json`
[
    {
        "VMware resource ID":  {
                                   "value":  "1233452"
                               }
    },
    {
        "VMware NIC index":  {
                                 "value":  "5"
                             }
    }
]

If you need more info, just ask.
-Ronald

**Comment by rmbolger** [comment]
Unless you made a typo in the issue text, I think you just have a few curly braces in the wrong place building the hashtable (which I do all the time with multiple layers of nested hashtables). It's a little easier to see if you expand it out on different lines. Your first one that is working looks like this:

```powershell
@{
    extattrs = @{
        "VMware resource ID" = @{value = "$persistentid"}
    }
}
```

The one that's not working currently looks like this:

```powershell
@{
    extattrs = @{
        "VMware resource ID" = @{value="$persistentid"}
    }
};
@{
    "VMware NIC index"= @{value="$VMNIC"}
}
```

The `VMware NIC index` is actually being treated as a whole separate PowerShell command rather than being included in the template object for `Set-IBObject`. You just need to move it back into the `extattrs` hashtable like this:

```powershell
@{
    extattrs = @{
        "VMware resource ID" = @{value="$persistentid"};
        "VMware NIC index" = @{value="$VMNIC"}
    }
}
```

And compressing that back down to a single line would look like this:

```powershell
@{extattrs=@{"VMware resource ID"=@{value="$persistentid"};"VMware NIC index"=@{value="$VMNIC"}}}
```

**Comment by resveld** [comment]
Thanks, will test tomorrow and let you know. Best regardsRonald-------- Oorspronkelijk bericht --------Onderwerp: Re: [rmbolger/Posh-IBWAPI] Question: add multiple extensible attributes on a single host record (#31)Van: Ryan Bolger Aan: rmbolger/Posh-IBWAPI Cc: resveld ,Author Unless you made a typo in the issue text, I think you just have a few curly braces in the wrong place building the hashtable (which I do all the time with multiple layers of nested hashtables). It's a little easier to see if you expand it out on different lines. Your first one that is working looks like this:
@{
    extattrs = @{
        "VMware resource ID" = @{value = "$persistentid"}
    }
}
The one that's not working currently looks like this:
@{
    extattrs = @{
        "VMware resource ID" = @{value="$persistentid"}
    }
};
@{
    "VMware NIC index"= @{value="$VMNIC"}
}
The VMware NIC index is actually being treated as a whole separate PowerShell command rather than being included in the template object for Set-IBObject. You just need to move it back into the extattrs hashtable like this:
@{
    extattrs = @{
        "VMware resource ID" = @{value="$persistentid"};
        "VMware NIC index" = @{value="$VMNIC"}
    }
}
And compressing that back down to a single line would look like this:
@{extattrs=@{"VMware resource ID"=@{value="$persistentid"};"VMware NIC index"=@{value="$VMNIC"}}}

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rmbolger/Posh-IBWAPI","title":"rmbolger/Posh-IBWAPI","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/rmbolger/Posh-IBWAPI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rmbolger in #31: Unless you made a typo in the issue text, I think you just have a few curly braces in the wrong place building the hashtable (which I do all the time with multiple layers of nested hashtables). It's a little easier to see if you expand it out on different lines. Your first one that is working looks like this:\r\n\r\n```powershell\r\n@{\r\n    extattrs = @{\r\n        \"VMware resource ID\" = @{value = \"$persistentid\"}\r\n    }\r\n}\r\n```\r\n\r\nThe one that's not working currently looks like this:\r\n\r\n```powershell\r\n@{\r\n    extattrs = @{\r\n        \"VMware resource ID\" = @{value=\"$persistentid\"}\r\n    }\r\n};\r\n@{\r\n    \"VMware NIC index\"= @{value=\"$VMNIC\"}\r\n}\r\n```\r\n\r\nThe `VMware NIC index` is actually being treated as a whole separate PowerShell command rather than being included in the template object for `Set-IBObject`. You just need to move it back into the `extattrs` hashtable like this:\r\n\r\n```powershell\r\n@{\r\n    extattrs = @{\r\n        \"VMware resource ID\" = @{value=\"$persistentid\"};\r\n        \"VMware NIC index\" = @{value=\"$VMNIC\"}\r\n    }\r\n}\r\n```\r\n\r\nAnd compressing that back down to a single line would look like this:\r\n\r\n```powershell\r\n@{extattrs=@{\"VMware resource ID\"=@{value=\"$persistentid\"};\"VMware NIC index\"=@{value=\"$VMNIC\"}}}\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/rmbolger/Posh-IBWAPI/issues/31#issuecomment-439095727"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rmbolger/Posh-IBWAPI/issues/31#issuecomment-439095727",
"url": "https://github.com/rmbolger/Posh-IBWAPI/issues/31#issuecomment-439095727",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [rmbolger/Posh-IBWAPI] Question: add multiple extensible attributes on a single host record (#31)",
"sections": [
{
"text": "",
"activityTitle": "**Ryan Bolger**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@rmbolger",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"rmbolger/Posh-IBWAPI\",\n\"issueId\": 31,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"rmbolger/Posh-IBWAPI\",\n\"issueId\": 31\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/rmbolger/Posh-IBWAPI/issues/31#issuecomment-439095727"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 410953289\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by resveld** [comment]
Thanks, that did the trick. Will close this one!
