### ISSUE TITLE
Find-IBRecord :Wrong Search String uri 

### ISSUE THREAD

**Issue by CermakPOI** [rmbolger/Posh-IBWAPI#32]
```
$FQDNCanonicalStatus = Find-IBRecord -Gridmaster $Gridmaster -Credential $PSCredential -SearchString "myserver.contoso.com"

VERBOSE: FIND-IBRECORD:  URI String:  https://Myintranet.com/wapi/v2.9/search?search_string~:=myserver.contoso.com

```

`search_string~:=` 
should be
`search_string:~=`

**Comment by rmbolger** [comment]
I'm confused. `Find-IBRecord` is not a function that exists in this module. Are you using another module or script that uses this one as a dependency?

**Comment by rmbolger** [comment]
I got your message via the PowerShell Gallery as well. Again, the `Find-IBRecord` function does not exist in this module. Can you post the code you're using somewhere?
