### ISSUE TITLE
IPv6?

### ISSUE THREAD

**Issue by khamilton59** [rmbolger/Posh-IBWAPI#41]
Any chance of adding IPv6 to this?  We're a mixed IPv4/IPv6 shop slowly migrating to IPv6.

**Comment by rmbolger** [comment]
I don't believe there are any changes necessary to support an IPv6 environment. Infoblox has supported IPv6 for quite a while. And the module is just making HTTP calls via `Invoke-RestMethod` under the hood which supports IPv6 endpoints as far as I'm aware.

Is there something in particular that's not working for you?

**Comment by khamilton59** [comment]
You are correct sir, my mistake.  The hosts I was querying for testing apparently didn't have v6 addresses assigned. 
I just did a full dump of a domain and I see the v6 addresses on things now.
