### ISSUE TITLE
Readme: no installation info about WAPI

### ISSUE THREAD

**Issue by BananaAcid** [rmbolger/Posh-IBWAPI#44]
I need to add devices to a IB grid. Using POSH. Installing this tool, and trying it out, it errors out saying WAPIVersion is not available.

The documentation defines, WAPI 1.4+ is required. But no where an info on what has to be downloaded additionally to get it working.

Infos would be helpfull.

**Comment by rmbolger** [comment]
The WAPI version is controlled by the version of NIOS installed on your grid. There's nothing additional you need to download in order to use the module. Could you copy and paste the command you ran and its output here? This sounds like a simple config issue we can work out.

**Comment by BananaAcid** [comment]
I will try the commands tomorrow again, but using config command on my workstation and notebook did not succeed. Both resulting in the same error. Using the web UI, I am able to add computers and modify existing. (Adding a new one and removing an old one, is what I have to do while traveling to the different production sites)

**Comment by rmbolger** [comment]
In order to help, I need to see the exact command you used and the exact output it produced. Can you copy and paste that into the issue thread here?

**Comment by BananaAcid** [comment]
I thought about testing the connection at all:
```
PS> Invoke-RestMethod https://10.xxx.xxx.xxx/wapi/v2.2/lease -Credential (Get-Credential)
Invoke-RestMethod : 
401 Authorization Required
Authorization Required
This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.
```

If this is how it should work, there seems to be something disabled on the server - the user interface works with my cerds.

**Comment by rmbolger** [comment]
Yes. If your credentials are correct and your account is setup properly, that query should not return an error. It's possible the group your account is a member of doesn't enable API Access. It's a check box in the Roles tab of a group's properties for `Allowed Interfaces`. On group creation, "GUI" is checked by default, but "API" is not.
