### ISSUE TITLE
typo in "The definitive list of REST examples" article of Wiki

### ISSUE THREAD

**Issue by igorchernysh** [rmbolger/Posh-IBWAPI#46]
Hi,
I believe there typo in:

# create a template to change the IP address
$template = @{ipv4addrs=@(**$**{ipv4addr='1.1.1.2'})}

, correct value will be:

$template = @{ipv4addrs=@(**@**{ipv4addr='1.1.1.2'})}

Thanks,
Igor.

**Comment by rmbolger** [comment]
Nice catch! Thanks. Fixed.
