### ISSUE TITLE
Errors thrown when attempting to Get Schema for WAPI v2.9

### ISSUE THREAD

**Issue by Chirishman** [rmbolger/Posh-IBWAPI#53]
What is the highest tested-good version of the api for use with this module?

I am getting a long list of errors when attempting to run the `Get-IBSchema` command for wapi v2.9 starting with the error shown below:

> Requested Version: 2.9
> 
> Supported Versions:
> 
> Exception calling "Remove" with "1" argument(s): "StartIndex cannot be less than zero.
> Parameter name: startIndex"
> At C:\Program Files\WindowsPowerShell\Modules\posh-ibwapi\Private\Format-Columns.ps1:67 char:53
> + ... th -gt $maxPossibleLength) { $_.Remove($maxPossibleLength-2) + '..' }
> +                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
>     + FullyQualifiedErrorId : ArgumentOutOfRangeException

**Comment by rmbolger** [comment]
Hi @Chirishman. I'm currently using it against my own grid which is currently on NIOS 8.5.2 (WAPI 2.11.1). But I've been running against that same grid through pretty much every version of 8.x as it was upgraded over time without issue. Can you provide some more detail on the command(s) you ran that generated the errors on your grid? Also, did you install the module via PowerShell Gallery or manually with the Github package?
