### ISSUE TITLE
Is it possible to return current lease Information?

### ISSUE THREAD

**Issue by KirkJohnson76** [rmbolger/Posh-IBWAPI#59]
Is there a way to return current lease information with Get-IBObject?   I've tried Get-IBObject -type lease and it just churns/returns nothing.

**Comment by KirkJohnson76** [comment]
Nevermind, Get-IBObject -type lease does indeed work, it just takes a minute to return anything.

**Comment by rmbolger** [comment]
Depending on the number of results, it may take several "pages" worth of queries to return all of the results unless you limit them with a `-Filters` or `-MaxResults` parameter. DHCP leases tend to be quite numerous in some environments. The default page size is 1000 objects. You can also see it churning through the pages if you add `-Verbose`.

**Comment by KirkJohnson76** [comment]
Anyway to include mac addresses on the lease details?  or to filter by a specific mac address?

**Comment by rmbolger** [comment]
Yes, that should work for filtering. If you want the field included in the results, you have to ask for it using `-ReturnFields` since it's not included in the base results.

```powershell
# get just the 'hardware' field
Get-IBObject -type lease -Filters 'hardware=00:10:40:xx:xx:xx' -ReturnFields hardware

# get base fields + hardware
Get-IBObject -type lease -Filters 'hardware=00:10:40:xx:xx:xx' -ReturnBaseFields -ReturnFields hardware
```
