### ISSUE TITLE
Add more newbie info to README and "definitive list"

### ISSUE THREAD

**Issue by frankhecker** [rmbolger/Posh-IBWAPI#9]
First, thanks very much for doing this. As a total PowerShell newbie I really appreciate having a WAPI interface I can use for the same sort of quick-and-dirty WAPI exploration I use curl for on OS X and Linux. Two minor things I think might further help newbies:

1. In the README include a brief mention of the trick to get JSON output (like people would be used to with curl). As I understand it, for quick and dirty use you could just use Get-IBObject ... | ConvertTo-Json.
2. In the "Definitive List" include a brief mention of -IgnoreCert. I've dealt with dozens of Infoblox customers, and the number who have valid CA-issued certificates for their GM could probably be counted on the finger of one hand.

**Comment by rmbolger** [comment]
Done and done.  =)
